import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      ><header id="header">
             <div id="maindiv">
                   <h1 id="tittle">Qaimudin</h1>
            <a id="a" href="/">Home</a>
         <a id="a" href="./About">About</a>
       <a id="a" href="./Contact">Contact</a>
    </div>
        </header>
     
        {children}
      </body>
    </html>
  );
}
